### ISSUE TITLE
pointing content models to an aliased environment

### ISSUE THREAD

**Issue by nivincp** [contentful-userland/contentful-action#11]
given a config like this https://i.imgur.com/Ooi26bt.png is it possible to point the master pattern to a specific env alias in gh actions? for example something like follows

```yaml
delete_feature: true
set_alias: true
**staging_pattern**: "staging-[YYYY]-[MM]-[DD]-[hh][mm][ss]"
feature_pattern: "gh-[branch]"
migrations_dir: src/migrations
space_id: "xxx"
management_api_key: "xxxx"
```

instead of `master_pattern` can we specify there is an aliased env and it needs to refer to that?
